# -*- coding: utf-8 -*-
"""HouseRent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CvrssL7-bxW6qPCm06JfAnmO_v4RjFRF
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df= pd.read_csv("USA_Housing.csv")
df.head(10)
df.info()
df.describe()
df.columns()
sns.pairplot(df)
sns.distplot(df['Price'])
sns.heatmap(df.corr(),annot=True)
sns.heatmap(df.corr(),annot=True)