# -*- coding: utf-8 -*-
"""WeatherPrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HzU45TuNgQDGG4eqZwU2as7boxvk_8FD
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df= pd.read_csv("Weather Dataset.csv")
df.head(10)
sns.histplot(df['Weather'])
plt.title("Weather data")
plt.show()

sns.histplot(df['Wind Speed_km/h'])
plt.title("Wind Speed")
plt.show()

sns.histplot(df['Visibility_km'])
plt.title("Visibility")
plt.show()


sns.histplot(df['Press_kPa'])
plt.title("Pressure")
plt.show()

sns.scatterplot(df['Temperature'],df['Humidity'])
plt.title("Temperature vs Humidity")
plt.show()

sns.barplot(df['Weather'],df['Temperature'])
plt.title("Weather vs Temperature")
plt.show()

sns.lineplot(df['Weather'],df['Humidity'])
plt.title("Weather vs Humidity")
plt.show()

sns.heatmap(df.corr(),annot=True)
plt.title("Correlation Heatmap")
plt.show()